### ISSUE TITLE
Installation failed: Command failed (1)

### ISSUE THREAD

**Issue by MaxSalm** [caravagn/BMix#1]
Hi there! On trying to install `BMix` for the first time, the following error is occuring:

```
Error: package or namespace load failed for 'BMix':
 .onLoad failed in loadNamespace() for 'BMix', details:
  call: NULL
  error: 'cli_alert_success' is not an exported object from 'namespace:cli'
```

This is likely due to an update to the `cli`/`cliapp` package. Hope this helps

**Comment by caravagn** [comment]
Hi, sorry I had missed this issue. I think it should all be working now.
